server:
  port: ${serverPort:8443}
  contextPath: ${serverContextPath:/}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

zuul:
  retryable: true
  sensitiveHeaders: 
  ribbonIsolationStrategy: SEMAPHORE
  routes:
    # Lookups
    computationsLookup:
      path: /service/lookup/computations/**
      serviceId: aqcu/lookup/computations
      stripPrefix: true
    controlConditionsLookup:
      path: /service/lookup/controlConditions/**
      serviceId: aqcu/lookup/controlConditions
      stripPrefix: true
    derivationChainFindLookup:
      path: /service/lookup/derivationChain/find/**
      serviceId: aqcu/lookup/derivationChain/find
      stripPrefix: true
    derivationChainRatingModelLookup:
      path: /service/lookup/derivationChain/ratingModel/**
      serviceId: aqcu/lookup/derivationChain/ratingModel
      stripPrefix: true
    fieldVisitDatesLookup:
      path: /service/lookup/field-visit-dates/**
      serviceId: aqcu/lookup/field-visit-dates
      stripPrefix: true
    periodsLookup:
      path: /service/lookup/periods/**
      serviceId: aqcu/lookup/periods
      stripPrefix: true
    sitesLookup:
      path: /service/lookup/sites/**
      serviceId: aqcu/lookup/sites
      stripPrefix: true
    timeseriesProcessorTypesLookup:
      path: /service/lookup/timeseries/processorTypes/**
      serviceId: aqcu/lookup/timeseries/processorTypes
      stripPrefix: true
    timeseriesIdentifiersLookup:
      path: /service/lookup/timeseries/identifiers/**
      serviceId: aqcu/lookup/timeseries/identifiers
      stripPrefix: true
    unitsLookup:
      path: /service/lookup/units/**
      serviceId: aqcu/lookup/units
      stripPrefix: true
    # Reports
    correctionsataglanceReport:
      path: /service/reports/correctionsataglance/**
      serviceId: aqcu/correctionsataglance
      stripPrefix: true
    derivationchainReport:
      path: /service/reports/derivationchain/**
      serviceId: aqcu/derivationchain
      stripPrefix: true
    dvhydrographReport:
      path: /service/reports/dvhydrograph/**
      serviceId: aqcu/dvhydro
      stripPrefix: true
    extremesReport:
      path: /service/reports/extremes/**
      serviceId: aqcu/extremes
      stripPrefix: true
    fiveyeargwsumReport:
      path: /service/reports/fiveyeargwsum/**
      serviceId: aqcu/fiveyeargwsum
      stripPrefix: true
    sensorreadingsummaryReport:
      path: /service/reports/sensorreadingsummary/**
      serviceId: aqcu/sensorreadingsummary
      stripPrefix: true
    sitevisitpeakReport:
      path: /service/reports/sitevisitpeak/**
      serviceId: aqcu/sitevisitpeak
      stripPrefix: true
    timeseriessummaryReport:
      path: /service/reports/timeseriessummary/**
      serviceId: aqcu/timeseriessummary
      stripPrefix: true
    uvhydrographReport:
      path: /service/reports/uvhydrograph/**
      serviceId: aqcu/uvhydrograph
      stripPrefix: true
    vdiagramReport:
      path: /service/reports/vdiagram/**
      serviceId: aqcu/vdiagram
      stripPrefix: true
    # Other
    health:
      path: /service/health/**
      serviceId: aqcu/aqcu-webservice/service/health
      stripPrefix: true
    echo:
      path: /service/echo/**
      serviceId: aqcu/aqcu-webservice/service/echo
      stripPrefix: true
    batch:
      path: /service/batch/**
      serviceId: aqcu/aqcu-webservice/service/batch
      stripPrefix: true

#Legacy Services
aqcu/aqcu-webservice/service/health:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

aqcu/aqcu-webservice/service/echo:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

aqcu/aqcu-webservice/service/batch:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

# New Services
aqcu/correctionsataglance:
  ribbon:
    listOfServers: ${corrReportServerList}
    IsSecure: ${corrReportIsSecure:true}

aqcu/derivationchain:
  ribbon:
    listOfServers: ${dcReportServerList}
    IsSecure: ${dcReportIsSecure:true}

aqcu/dvhydro:
  ribbon:
    listOfServers: ${dvhydroReportServerList}
    IsSecure: ${dvhydroReportIsSecure:true}

aqcu/extremes:
  ribbon:
    listOfServers: ${extReportServerList}
    IsSecure: ${extReportIsSecure:true}

aqcu/fiveyeargwsum:
  ribbon:
    listOfServers: ${fiveYearReportServerList}
    IsSecure: ${fiveYearReportIsSecure:true}

aqcu/sensorreadingsummary:
  ribbon:
    listOfServers: ${srsReportServerList}
    IsSecure: ${srsReportIsSecure:true}

aqcu/sitevisitpeak:
  ribbon:
    listOfServers: ${svpReportServerList}
    IsSecure: ${svpReportIsSecure:true}
    
aqcu/timeseriessummary:
  ribbon:
    listOfServers: ${tssReportServerList}
    IsSecure: ${tssReportIsSecure:true}

aqcu/uvhydrograph:
  ribbon:
    listOfServers: ${uvhydroReportServerList}
    IsSecure: ${uvhydroReportIsSecure:true}

aqcu/vdiagram:
  ribbon:
    listOfServers: ${vdiReportServerList}
    IsSecure: ${vdiReportIsSecure:true}

aqcu/lookup/computations:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/controlConditions:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/derivationChain/find:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/derivationChain/ratingModel:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/field-visit-dates:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/periods:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/sites:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/timeseries/processorTypes:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/timeseries/identifiers:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/lookup/units:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

lambda:
  region: "us-west-2"
  functions:
    gwvisitreviewstatus: "VRStatReportFunction"

eureka:
  client:
    enabled: false

ribbon:
  MaxAutoRetries: ${ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${ribbonConnectTimeout}
  ReadTimeout: ${ribbonReadTimeout}
  OkToRetryOnAllOperations: true

aqcu:
  login:
    url: ${aqcuLoginUrl:https://localhost:443/}

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}

management:
  security:
    enabled: false

spring:
  profiles:
    active: default
  application:
    name: aqcu-gateway
  jmx:
    default-domain: aqcu-gateway
